# Generated by Django 3.0.4 on 2020-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.CharField(choices=[('electronics', 'electronics'), ('fashion', 'fashion'), ('food', 'food')], max_length=20),
        ),
    ]
