# Generated by Django 3.0.4 on 2020-05-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200507_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='li',
            new_name='category',
        ),
    ]
