# Generated by Django 3.0.4 on 2020-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200507_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
