# Generated by Django 3.0.4 on 2020-05-07 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200507_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordertime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
