# Generated by Django 3.0.4 on 2020-05-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200510_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cropping',
        ),
    ]
